### ISSUE TITLE
Update to R5?

### ISSUE THREAD

**Issue by godsyn** [ltguide/CraftBukkit-MineBackup#19]
```
Minecraft dev server launched.
174 recipes
27 achievements
16:05:14 [INFO] Starting minecraft server version 1.1
16:05:14 [INFO] Loading properties
16:05:14 [INFO] Starting Minecraft server on *:25569
16:05:15 [INFO] This server is running CraftBukkit version git-Bukkit-1.1-R4-13-g6381da2-b1952jnks (MC: 1.1) (Implementing API version 1.1-R5-SNAPSHOT)
16:05:15 [INFO] Preparing level "world"
16:05:15 [INFO] Default game type: 0
16:05:15 [INFO] Preparing start region for level 0 (Seed: -97394964482756812)
16:05:15 [INFO] Preparing start region for level 1 (Seed: -97394964482756812)
16:05:16 [INFO] Preparing start region for level 2 (Seed: -97394964482756812)
16:05:16 [INFO] Preparing spawn area: 20%
16:05:16 [INFO] [MineBackup] Loading MineBackup v0.4.8.4.
16:05:16 [INFO] [MineBackup] Loading configuration...
16:05:16 [SEVERE] Error occurred while enabling MineBackup v0.4.8.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/util/config/Configuration
        at alexoft.Minebackup.Config.loadConfig(Config.java:66)
        at alexoft.Minebackup.Config.<init>(Config.java:22)
        at alexoft.Minebackup.MineBackup.onEnable(MineBackup.java:25)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:364)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:225)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:208)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.config.Configuration
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 13 more
16:05:16 [INFO] Server permissions file permissions.yml is empty, ignoring it
16:05:16 [INFO] Done (1.445s)! For help, type "help" or "?"
```

**Comment by acstache** [comment]
try using the current version, 5.5, you're running 4.8.4 before all the changes were made.
http://dev.bukkit.org/server-mods/minebackup/files/

**Comment by godsyn** [comment]
Still has issues after updating. Will paste log later today.
On Feb 21, 2012 10:48 PM, "Brian" <
reply@reply.github.com>
wrote:

**Comment by acstache** [comment]
godsyn after looking at the code, it's not updated to the new Configuration system or the new Event system. That will have to be updated in order to work on the build of CB you're running. I'd suggest either downgrading your CB so everything still works, or uninstall this plugin for the time being.

see here for why plugins break beyond the stable 1.1-R4 if you haven't yet:
http://forums.bukkit.org/threads/beyond-craftbukkit-1-1-r4.60377/

**Comment by godsyn** [comment]
Yep, just ensuring there are plans to update when the time comes.

With 5.5:

```
Minecraft dev server launched.
174 recipes
27 achievements
11:43:16 [INFO] Starting minecraft server version 1.1
11:43:16 [INFO] Loading properties
11:43:16 [INFO] Starting Minecraft server on *:25569
11:43:16 [INFO] This server is running CraftBukkit version git-Bukkit-1.1-R4-13-                                             g6381da2-b1952jnks (MC: 1.1) (Implementing API version 1.1-R5-SNAPSHOT)
11:43:16 [INFO] Preparing level "world"
11:43:16 [INFO] Default game type: 0
11:43:16 [INFO] Preparing start region for level 0 (Seed: -97394964482756812)
11:43:17 [INFO] Preparing start region for level 1 (Seed: -97394964482756812)
11:43:17 [INFO] Preparing start region for level 2 (Seed: -97394964482756812)
11:43:17 [INFO] Preparing spawn area: 20%
11:43:18 [INFO] [MineBackup] Loading MineBackup v0.5.5.
11:43:18 [SEVERE] Error occurred while enabling MineBackup v0.5.5 (Is it up to d                                             ate?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:787)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14                                             2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:447)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.                                             java:41)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoad                                             er.java:239)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.                                             java:37)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.                                             java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at ltguide.minebackup.MineBackup.onEnable(MineBackup.java:50)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader                                             .java:343)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage                                             r.java:364)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:225)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:208                                             )
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerListe                                             ner
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.                                             java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.                                             java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 26 more
11:43:18 [INFO] Server permissions file permissions.yml is empty, ignoring it
11:43:18 [INFO] Done (1.482s)! For help, type "help" or "?"
```

**Comment by dredhorse** [comment]
hi, try 0.5.7 from the comments which has ftp and R5
