### ISSUE TITLE
Testing R5 Builds - Error Report

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#21]
What steps will reproduce the problem?
1. Install Java 7 Update 3 64Bit
2. Install CB 1964 server
3. Install MineBackup 0.5.5
4. Run server

What is the expected output? What do you see instead?
I hoped it will work with R5 API

What version of the product are you using?
MineBackup 0.5.5

Do you have an error log of what happened?
2012-02-28 15:33:18 [INFO] [MineBackup] Enabling MineBackup v0.5.5
2012-02-28 15:33:18 [SEVERE] Error occurred while enabling MineBackup v0.5.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:239)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:37)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at ltguide.minebackup.MineBackup.onEnable(MineBackup.java:50)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:364)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:227)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:210)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerListener
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 26 more

Please provide any additional information below.
Please update this awesome plugin since it has saved me time and its pretty easy to use. Also has a ton of features.

Thanks

**Comment by dredhorse** [comment]
hi, try 0.5.7 from the comments which has ftp and R5
