### ISSUE TITLE
java.io.IOException and  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#3]
2012-01-18 11:29:17 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:29:17 [INFO] [MineBackup]  \* compressing plugins
2012-01-18 11:29:23 [INFO] [MineBackup]     \ failed
2012-01-18 11:29:23 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:29:23 [SEVERE] [MineBackup] DEBUG: compress: .\plugins -> Minebackup\plugins\plugins_2012-01-18_11-29.zip
2012-01-18 11:29:23 [SEVERE] [MineBackup] java.io.IOException: The process cannot access the file because another process has locked a portion of the file
2012-01-18 11:29:23 [SEVERE] [MineBackup]   java.io.FileInputStream.readBytes(Native Method)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   java.io.FileInputStream.read(Unknown Source)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   java.io.BufferedInputStream.read1(Unknown Source)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   java.io.BufferedInputStream.read(Unknown Source)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   java.io.FilterInputStream.read(Unknown Source)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipFile(ZipUtils.java:95)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:80)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:76)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:46)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.process(TaskProcess.java:190)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 11:29:23 [SEVERE] [MineBackup]   java.lang.Thread.run(Unknown Source)
2012-01-18 11:29:23 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:29:23 [INFO] [MineBackup]  \* saving world
2012-01-18 11:29:23 [INFO] [MineBackup]  \* compressing world
2012-01-18 11:29:26 [INFO] [MineBackup]  \* saving world_nether
2012-01-18 11:29:26 [INFO] [MineBackup]  \* compressing world_nether
2012-01-18 11:29:26 [INFO] [MineBackup]  \* saving world_the_end
2012-01-18 11:29:26 [INFO] [MineBackup]  \* compressing world_the_end
2012-01-18 11:29:26 [INFO] [MineBackup]  \* saving creative
2012-01-18 11:29:26 [SEVERE] java.util.ConcurrentModificationException
2012-01-18 11:29:26 [SEVERE]    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
2012-01-18 11:29:26 [SEVERE]    at java.util.HashMap$KeyIterator.next(Unknown Source)
2012-01-18 11:29:26 [SEVERE]    at net.minecraft.server.World.a(World.java:2351)
2012-01-18 11:29:26 [SEVERE]    at net.minecraft.server.ChunkLoader.a(SourceFile:140)
2012-01-18 11:29:26 [SEVERE]    at net.minecraft.server.ChunkRegionLoader.a(SourceFile:84)
2012-01-18 11:29:26 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunk(ChunkProviderServer.java:163)
2012-01-18 11:29:26 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunks(ChunkProviderServer.java:212)
2012-01-18 11:29:26 [SEVERE]    at net.minecraft.server.World.save(World.java:273)
2012-01-18 11:29:26 [SEVERE]    at org.bukkit.craftbukkit.CraftWorld.save(CraftWorld.java:549)
2012-01-18 11:29:26 [SEVERE]    at ltguide.minebackup.TaskProcess.process(TaskProcess.java:168)
2012-01-18 11:29:26 [SEVERE]    at ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 11:29:26 [SEVERE]    at ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 11:29:26 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 11:29:26 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2012-01-18 11:29:26 [INFO] [MineBackup]  \* compressing creative
2012-01-18 11:29:31 [INFO] [MineBackup]  \* saving survival
2012-01-18 11:29:31 [INFO] [MineBackup]  \* compressing survival
2012-01-18 11:29:32 [INFO] [MineBackup] All backup actions have completed.

2012-01-18 11:34:03 [INFO] [MineBackup]  \* copying plugins
2012-01-18 11:34:03 [INFO] [MineBackup]     \ failed
2012-01-18 11:34:03 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:34:03 [SEVERE] [MineBackup] DEBUG: copy: .\plugins -> Minebackup\plugins\2012-01-18_11-34
2012-01-18 11:34:03 [SEVERE] [MineBackup] java.io.IOException: The process cannot access the file because another process has locked a portion of the file
2012-01-18 11:34:03 [SEVERE] [MineBackup]   java.io.FileInputStream.readBytes(Native Method)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   java.io.FileInputStream.read(Unknown Source)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   ltguide.minebackup.utils.DirUtils.copyFile(DirUtils.java:41)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   ltguide.minebackup.utils.DirUtils.copyDir(DirUtils.java:30)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   ltguide.minebackup.utils.DirUtils.copyDir(DirUtils.java:29)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.process(TaskProcess.java:189)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 11:34:03 [SEVERE] [MineBackup]   java.lang.Thread.run(Unknown Source)
2012-01-18 11:34:03 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:34:03 [INFO] [MineBackup]  \* compressing plugins
2012-01-18 11:34:09 [INFO] [MineBackup]     \ failed
2012-01-18 11:34:09 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:34:09 [SEVERE] [MineBackup] DEBUG: compress: .\plugins -> Minebackup\plugins\2012-01-18_11-34.zip
2012-01-18 11:34:09 [SEVERE] [MineBackup] java.io.IOException: The process cannot access the file because another process has locked a portion of the file
2012-01-18 11:34:09 [SEVERE] [MineBackup]   java.io.FileInputStream.readBytes(Native Method)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   java.io.FileInputStream.read(Unknown Source)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   java.io.BufferedInputStream.read1(Unknown Source)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   java.io.BufferedInputStream.read(Unknown Source)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   java.io.FilterInputStream.read(Unknown Source)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipFile(ZipUtils.java:95)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:80)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:76)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:46)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.process(TaskProcess.java:190)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 11:34:09 [SEVERE] [MineBackup]   java.lang.Thread.run(Unknown Source)
2012-01-18 11:34:09 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 11:34:09 [INFO] [MineBackup]  \* saving world
2012-01-18 11:34:09 [INFO] [MineBackup]  \* compressing world
2012-01-18 11:34:12 [INFO] [MineBackup]  \* saving world_nether
2012-01-18 11:34:12 [INFO] [MineBackup]  \* compressing world_nether
2012-01-18 11:34:12 [INFO] [MineBackup]  \* saving world_the_end
2012-01-18 11:34:12 [INFO] [MineBackup]  \* compressing world_the_end
2012-01-18 11:34:12 [INFO] [MineBackup]  \* saving creative
2012-01-18 11:34:12 [INFO] [MineBackup]  \* compressing creative
2012-01-18 11:34:17 [INFO] [MineBackup]  \* saving survival
2012-01-18 11:34:17 [INFO] [MineBackup]  \* compressing survival
2012-01-18 11:34:18 [INFO] [MineBackup] All backup actions have completed.

Configuration
# For an explanation of these settings, visit https://github.com/ltguide/CraftBukkit-MineBackup/wiki/Configuration

default_actions:
  save: false
  copy: false
  compress: false
  dropbox: false
default_settings:
  save: 15m
  copy: 10800
  compress: 10800
  compression_level: 9
  dropbox: '3:00'
  keep: 8
worlds:
  world:
    save: true
    compress: true
  world_nether:
    save: true
    compress: true
  world_the_end:
    save: true
    compress: true
  creative:
    save: true
    compress: true
  survival:
    save: true
    compress: true
others:
  plugins:
    copy: true
    compress: true
    dropbox: false
    exclude-folders:
    - tiles
    exclude-types:
    - jar
directories:
  worlds: .
  others: .
  destination: Minebackup
destination:
  format: '%Y-%M-%D_%H-%m'
  prepend-world: true
messages:
  prefix: '&e[MineBackup]&f'
  busy: An action is currently in progress. Try again in a few seconds.
  syntax: '&6Syntax: &f%s &6--&e %s'
  permission: '&cYou do not have permission.'
  status: '&6%s: &f%s (&edirty: &f%s) %s'
  status_action: '&6%s: &f%s (&e%s&f)&6; '
  status_time_under: waiting %s
  status_time_over: soon (%s over)
  status_time_none: not scheduled
  status_note: New actions will be scheduled once a minute.
  backup_now: All backup actions will start momentarily. (%s)
  backup_soon: All backup actions added to the queue. (%s)
  backup_next: The next backup action has been started early. (%s)
  backup_done: All backup actions have completed.
  reload: '&aReloaded configuration. (%s)'
  dropbox: Dropbox authentication completed. (%s)
commands:
  status:
    description: Display the scheduled time and interval for each action in the queue.
  now:
    description: Expire all action times and trigger them NOW.
    broadcast: users
  soon:
    description: Expire all action times so that they will trigger on the following queue checks.
    broadcast: admins
  next:
    description: Trigger the next action in the queue. If no time is expired then nothing will happen.
    broadcast: admins
  reload:
    description: Reload configuration and reset queue to configured intervals.
    broadcast: false
  dropbox:
    description: Add Dropbox authentication tokens. Visit http://minebackup-dropbox.appspot.com/ for values.
    broadcast: false
debug: false
version-nomodify: 0.5.1

Questions:
1. Can you make a setting like in the 0.4.8.4 version where I can put the .zip files all in one folder not separate folders? but still have a separate folder for plugin .zip files?

**Comment by ghost** [comment]
Also I can't seem to find the 0.5.2 version that you suggested to another guy.

**Comment by ltguide** [comment]
```
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
```

I'll have to quietly catch that specifically. It's probably a db file from a plugin.

In the meantime, I'm curious if v0.5.2 will fix your other exception. The link is at the bottom of [dev page](http://dev.bukkit.org/server-mods/minebackup/pages/v0-5-development/).

As far as question 1 goes, I don't recall such an option existing :0 What's the reason you would want all the world zips in one folder? The way it is now [WorldEdit](http://wiki.sk89q.com/wiki/WorldEdit/Snapshots) is compatible.

**Comment by ghost** [comment]
Nope, same thing.

2012-01-18 12:14:21 [INFO] [MineBackup] All backup actions will start momentarily. (KJanar)
2012-01-18 12:14:26 [INFO] [MineBackup]  \* copying plugins
2012-01-18 12:14:26 [INFO] [MineBackup]     \ failed
2012-01-18 12:14:26 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 12:14:26 [SEVERE] [MineBackup] DEBUG: copy: .\plugins -> Minebackup\plugins\2012-01-18_12-14
2012-01-18 12:14:26 [SEVERE] [MineBackup] java.io.IOException: The process cannot access the file because another process has locked a portion of the file
2012-01-18 12:14:26 [SEVERE] [MineBackup]   java.io.FileInputStream.readBytes(Native Method)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   java.io.FileInputStream.read(Unknown Source)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   ltguide.minebackup.utils.DirUtils.copyFile(DirUtils.java:41)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   ltguide.minebackup.utils.DirUtils.copyDir(DirUtils.java:30)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   ltguide.minebackup.utils.DirUtils.copyDir(DirUtils.java:29)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.process(TaskProcess.java:192)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 12:14:26 [SEVERE] [MineBackup]   java.lang.Thread.run(Unknown Source)
2012-01-18 12:14:26 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 12:14:27 [INFO] [MineBackup]  \* compressing plugins
2012-01-18 12:14:32 [INFO] [MineBackup]     \ failed
2012-01-18 12:14:32 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 12:14:32 [SEVERE] [MineBackup] DEBUG: compress: .\plugins -> Minebackup\plugins\2012-01-18_12-14.zip
2012-01-18 12:14:32 [SEVERE] [MineBackup] java.io.IOException: The process cannot access the file because another process has locked a portion of the file
2012-01-18 12:14:32 [SEVERE] [MineBackup]   java.io.FileInputStream.readBytes(Native Method)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   java.io.FileInputStream.read(Unknown Source)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   java.io.BufferedInputStream.read1(Unknown Source)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   java.io.BufferedInputStream.read(Unknown Source)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   java.io.FilterInputStream.read(Unknown Source)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipFile(ZipUtils.java:95)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:80)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:76)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.utils.ZipUtils.zipDir(ZipUtils.java:46)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.process(TaskProcess.java:193)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 12:14:32 [SEVERE] [MineBackup]   java.lang.Thread.run(Unknown Source)
2012-01-18 12:14:32 [SEVERE] [MineBackup] ---------------------------------------
2012-01-18 12:14:32 [INFO] [MineBackup]  \* saving world
2012-01-18 12:14:32 [INFO] [MineBackup]  \* compressing world
2012-01-18 12:14:35 [INFO] [MineBackup]  \* saving world_nether
2012-01-18 12:14:35 [SEVERE] java.util.ConcurrentModificationException
2012-01-18 12:14:35 [SEVERE]    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
2012-01-18 12:14:35 [SEVERE]    at java.util.HashMap$KeyIterator.next(Unknown Source)
2012-01-18 12:14:35 [SEVERE]    at net.minecraft.server.World.a(World.java:2351)
2012-01-18 12:14:35 [SEVERE]    at net.minecraft.server.ChunkLoader.a(SourceFile:140)
2012-01-18 12:14:35 [SEVERE]    at net.minecraft.server.ChunkRegionLoader.a(SourceFile:84)
2012-01-18 12:14:35 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunk(ChunkProviderServer.java:163)
2012-01-18 12:14:35 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunks(ChunkProviderServer.java:212)
2012-01-18 12:14:35 [SEVERE]    at net.minecraft.server.World.save(World.java:273)
2012-01-18 12:14:35 [SEVERE]    at org.bukkit.craftbukkit.CraftWorld.save(CraftWorld.java:549)
2012-01-18 12:14:35 [SEVERE]    at ltguide.minebackup.TaskProcess.process(TaskProcess.java:170)
2012-01-18 12:14:35 [SEVERE]    at ltguide.minebackup.TaskProcess.runQuick(TaskProcess.java:141)
2012-01-18 12:14:35 [SEVERE]    at ltguide.minebackup.TaskProcess.run(TaskProcess.java:101)
2012-01-18 12:14:35 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 12:14:35 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2012-01-18 12:14:35 [INFO] [MineBackup]  \* compressing world_nether
2012-01-18 12:14:35 [INFO] [MineBackup]  \* saving world_the_end
2012-01-18 12:14:35 [INFO] [MineBackup]  \* compressing world_the_end
2012-01-18 12:14:36 [INFO] [MineBackup]  \* saving creative
2012-01-18 12:14:36 [INFO] [MineBackup]  \* compressing creative
2012-01-18 12:14:40 [INFO] [MineBackup]  \* saving survival
2012-01-18 12:14:40 [INFO] [MineBackup]  \* compressing survival
2012-01-18 12:14:41 [INFO] [MineBackup] All backup actions have completed.

**Comment by ltguide** [comment]
Okay. I'll have to rework the threading a bit.

**Comment by ghost** [comment]
OK thanks. if you need some instant and fast answers add me on niftygamerz@live.com

**Comment by ltguide** [comment]
I think I've got it. [dev page](http://dev.bukkit.org/server-mods/minebackup/pages/v0-5-development/)
