### ISSUE TITLE
java.util.ConcurrentModificationException when saving a map with players online

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#4]
2012-01-18 12:35:00 [INFO] [MineBackup]  \* saving world_nether
2012-01-18 12:35:00 [SEVERE] java.util.ConcurrentModificationException
2012-01-18 12:35:00 [SEVERE]    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
2012-01-18 12:35:00 [SEVERE]    at java.util.HashMap$KeyIterator.next(Unknown Source)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.World.a(World.java:2351)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkLoader.a(SourceFile:140)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkRegionLoader.a(SourceFile:84)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunk(ChunkProviderServer.java:163)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunks(ChunkProviderServer.java:212)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.World.save(World.java:273)
2012-01-18 12:35:00 [SEVERE]    at org.bukkit.craftbukkit.CraftWorld.save(CraftWorld.java:549)
2012-01-18 12:35:00 [SEVERE]    at ltguide.minebackup.TaskProcess.process(TaskProcess.java:170)
2012-01-18 12:35:00 [SEVERE]    at ltguide.minebackup.TaskProcess.runOnce(TaskProcess.java:117)
2012-01-18 12:35:00 [SEVERE]    at ltguide.minebackup.TaskProcess.run(TaskProcess.java:104)
2012-01-18 12:35:00 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 12:35:00 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2012-01-18 12:35:00 [SEVERE] java.util.ConcurrentModificationException
2012-01-18 12:35:00 [SEVERE]    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
2012-01-18 12:35:00 [SEVERE]    at java.util.HashMap$KeyIterator.next(Unknown Source)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.World.a(World.java:2351)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkLoader.a(SourceFile:140)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkRegionLoader.a(SourceFile:84)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunk(ChunkProviderServer.java:163)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.ChunkProviderServer.saveChunks(ChunkProviderServer.java:212)
2012-01-18 12:35:00 [SEVERE]    at net.minecraft.server.World.save(World.java:273)
2012-01-18 12:35:00 [SEVERE]    at org.bukkit.craftbukkit.CraftWorld.save(CraftWorld.java:549)
2012-01-18 12:35:00 [SEVERE]    at ltguide.minebackup.TaskProcess.process(TaskProcess.java:170)
2012-01-18 12:35:00 [SEVERE]    at ltguide.minebackup.TaskProcess.runOnce(TaskProcess.java:117)
2012-01-18 12:35:00 [SEVERE]    at ltguide.minebackup.TaskProcess.run(TaskProcess.java:104)
2012-01-18 12:35:00 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-01-18 12:35:00 [SEVERE]    at java.lang.Thread.run(Unknown Source)

**Comment by ltguide** [comment]
#3 duplicate?
